---
title: "vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(mastersproject)
```

# Creating a Single Tile Map

```{r}
us <- spData::us_states %>%
  arrange(NAME) %>%
  mutate(abbreviation = c("AL", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "ID", 
                          "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN",
                          "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND",
                          "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VE",
                          "VA", "WA", "WV", "WI", "WY"))

# choose coordinate projection
us_3857 <- st_transform(us, 3857)

# create tile map
us_3857 <- us_3857 %>%
  mutate(tile_map = generate_map(us_3857$geometry, square = FALSE, flat_topped = TRUE,
                                 prop = 0.05, interpolate = 1, smoothness = 5, shift = c(0,0)))

# plot tile map
ggplot(us_3857) +
  geom_sf(aes(geometry = tile_map)) +
  geom_sf_text(aes(geometry = tile_map, label = abbreviation),
               fun.geometry = function(x) sf::st_centroid(x))
```

# Creating Many Tile Maps

```{r}
# create and plot many tile maps
us_maps <- many_maps(us_3857$geometry, us_3857$abbreviation, prop = 0.1, interpolate = c(0.75,1), smoothness = 0,
                     shift = list(c(0,0), c(0.5,0), c(0,0.5)), weights = c(1,1,1,1), plot = TRUE)

# choose tile map and add to original data
us_3857 <- us_3857 %>%
  mutate(square_map = us_maps$map[[1]])

# plot tile map
ggplot(us_3857) +
  geom_sf(aes(geometry = square_map)) +
  geom_sf_text(aes(geometry = square_map, label = abbreviation))
```

